name: "pointnet2_onnx_alternative"
backend: "python"
max_batch_size: 32 

input [
  {
    name: "points"
    data_type: TYPE_FP32
    dims: [ -1, 6 ] 
  }
]

output [
  {
    name: "segmentation_output"
    data_type: TYPE_FP32
    dims: [ -1, 5 ] #Change it to your target number
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 2000  
  preferred_batch_size: [ 4, 8, 16, 32 ]  
}

instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]
